version: '3' # 表示该 Docker-Compose 文件使用的是 Version 3 file

#volumes: # 卷挂载路径
#  xxljob_mysql-vol: # xxl-job
#  nacos_mysql-vol: # nacos
#  redis_data-vol: # redis
#  rocket_mq-vol: # rocket-mq
#  elastic_search-vol: # es

services:

  ######################################################################################################    ELK 开始

  elk_elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elk_elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ./env/elk/es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./env/elk/es/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9206:9200
      - 9306:9300
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.6.2

  elk_logstash:
    image: logstash:7.6.2
    container_name: elk_logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./env/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elk_elasticsearch #kibana在elasticsearch启动之后再启动
    ports:
      - 4560:4560
      - 9601:9600
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.6.3
  elk_kibana:
    image: kibana:7.6.2
    container_name: elk_kibana
    depends_on:
      - elk_elasticsearch #kibana在elasticsearch启动之后再启动
    volumes:
      - ./env/elk/etc/localtime:/etc/localtime
      - ./env/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5603:5601
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.6.4
  ######################################################################################################    ELK 结束

networks:
  extnetwork:
    name: goodess_net  #网络名称
    ipam:
      config:
        - subnet: 172.18.0.0/16 # 网络号段
          gateway: 172.18.0.1 # 网关地址