version: '3' # 表示该 Docker-Compose 文件使用的是 Version 3 file

#volumes: # 卷挂载路径
#  xxljob_mysql-vol: # xxl-job
#  nacos_mysql-vol: # nacos
#  redis_data-vol: # redis
#  rocket_mq-vol: # rocket-mq
#  elastic_search-vol: # es

services:

  ######################################################################################################  nacos集群 开始
  nacos_server_0:
    image: nacos/nacos-server:2.0.0
    hostname: nacos_server_0
    container_name: nacos_server_0
    ports:
      - "8850:8848"
      - "9557:9555"
    environment:
      PREFER_HOST_MODE: ip #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
      NACOS_SERVERS: 172.18.1.4:8848  #集群中其它节点[ip1:port ip2:port]
      MYSQL_SERVICE_HOST: 172.18.1.3
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: goddess_root
    volumes:
      - ./env/nacos/server0/data:/data
#      - ./env/nacos/server0/logs:/home/nacos/logs #日志输出目录
      - ./env/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties #custom.properties内包含很多自定义配置，可按需配置
    depends_on:
      - nacos_mysql_master
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.1.5

  nacos_server_1:
    image: nacos/nacos-server:2.0.0
    hostname: nacos_server_1
    container_name: nacos_server_1
    ports:
      - "8849:8848"
      - "9556:9555"
    environment:
      PREFER_HOST_MODE: ip #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
      NACOS_SERVERS: 172.18.1.5:8848  #集群中其它节点[ip1:port ip2:port]
      MYSQL_SERVICE_HOST: 172.18.1.3
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: goddess_root
    volumes:
      - ./env/nacos/server1/data:/data
#      - ./env/nacos/server1/logs:/home/nacos/logs #日志输出目录
      - ./env/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties/ #custom.properties内包含很多自定义配置，可按需配置
    depends_on:
      - nacos_mysql_master
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.1.4

  nacos_mysql_master:
    image: mysql:5
    ports:
      - "3307:3306"
    hostname: nacos_mysql_master
    container_name: nacos_mysql_master
    environment:
      MYSQL_DATABASE: nacos
      MYSQL_ROOT_PASSWORD: goddess_root
      TZ: Asia/Shanghai
    volumes:
      - ./env/nacos/mysql/master/:/var/lib/mysql
      - ./env/nacos/nacos-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.1.3

  nacos_nginx:
    image: nginx:1.19.2-alpine
    hostname: nacos_nginx
    container_name: nacos_nginx
    volumes:
      - ./env/nacos/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./env/nacos/nginx/log:/var/log/nginx
    ports:
      - "8848:80"
    depends_on:
      - nacos_server_0
      - nacos_server_1
    #restart: always
    networks:
      extnetwork:
        ipv4_address: 172.18.1.2
  ######################################################################################################  nacos集群 结束
networks:
  extnetwork:
    name: goodess_net  #网络名称
    ipam:
      config:
        - subnet: 172.18.0.0/16 # 网络号段
          gateway: 172.18.0.1 # 网关地址